server:
  port: 8091
  servlet:
    context-path: /
  tomcat:
    #最大线程数
    max-threads: 1000
    #最大连接数
    max-connections: 20000
    #最大全接连数(TCP)
    accept-count: 8000
    uri-encoding: UTF-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名
  mapper-locations: classpath:mapper/*.xml
spring:
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 799520wyp
    url: jdbc:mysql://localhost:3306/scenicareamanagement?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  devtools:
    #热部署生效,默认就是true
    restart:
      enabled: true
  redis:
    host: 47.110.241.39
#    host: 192.168.190.112
    port: 6379
#    password: hwadee@2023
    password: xhl@myRedis123
    database: 1
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 1
  servlet:
      multipart:
        max-file-size: 100MB
        enabled: true
        location: src/main/resources/static/uploads/  # 设置上传文件的存储路径

#logback
logging:
  level:
    com.hwadee.springboot: debug
  #将日志输出到文件
  config: classpath:logback-spring.xml
